spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hourglass_weaver_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Yly030909

mybatis:
  configuration:
    map-underscore-to-camel-case: true